# Aquarius - Automation Simplified
#
# @brief Git script for exporting PCB data for Power Module
# @date 5/16/25
# @author cyberreefguru
# (c) CRG Makes 2025
name: Aquarius Power Module CI
on:
  push:
    paths:
      - 'pcb/power-module.kicad_sch'
      - 'pcb/power-module.kicad_pcb'
      - 'pcb/power-module.kibot.yaml'
      - '.github/workflows/power-module.yaml'
  workflow_dispatch:
  release:
    types: [ published ]
    
jobs:
  export-ecad:
    name: Export ECAD
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
      
    steps:
    - name: Generate Short SHA Environment Variable
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      
    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        apt -y install git git-lfs zip librsvg2-bin imagemagick
        git lfs install
        #mkdir -p /usr/share/fonts/kibot

    - name: Checkout Power Module Repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Checkout Extras
      uses: actions/checkout@v4
      with:
        repository: crgmakes/kicad-extras
        path: extras

    - name: Checkout CRGM Library
      uses: actions/checkout@v4
      with:
        repository: crgmakes/kicad-library
        path: crgm

    - name: Checkout PcbDraw Library
      uses: actions/checkout@v4
      with:
        repository: yaqwsx/PcbDraw-Lib
        path: pcbdraw

    - name: Get 3d packages
      run: |
        git clone https://gitlab.com/kicad/libraries/kicad-packages3D.git
        mkdir -p /usr/share/kicad/3dmodels
        mv ./kicad-packages3D/* /usr/share/kicad/3dmodels

    - name: Update fonts
      run: |
        mkdir -p /usr/share/fonts/
        cp extras/fonts/* /usr/share/fonts/
        fc-cache -f -v
        ls -AlF pcbdraw/
        # ls -AlF crgm/
        ls -AlF crgm/models/
        # ls -AlF /usr/share/kicad
        ls -AlF /usr/share/kicad/3dmodels/

    - name: Update the PCBs with on default branch with git hash
      # if: github.event_name == 'release' || steps.extract_branch.outputs.branch == env.main_branch
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"    
        echo "ref: ${{ github.ref }}"
        echo "default: ${{ env.default }}"
        sed -i "s!<<hash>>!${COMMIT}!" pcb/power-module.kicad_pcb
        sed -i.bak 's|\${KICAD_USER_MODEL_DIR}|../crgm/models|g' pcb/power-module.kicad_pcb

    - name: Generate Export Files
      run: |
        cd pcb
        rm -rf production/
        kibot -c power-module.kibot.yaml -e power-module.kicad_sch -b power-module.kicad_pcb -d production
        cd production
        zip -r -j ../aquarius-power-module-fab.zip fab
        zip -r -j ../aquarius-power-module-pnp.zip pnp
        cd doc
        zip -r ../../aquarius-power-module-doc.zip .
    #   zip -r -j aquarius-power-module-pcb.zip production/

# Upload
    - name: Upload Files as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aquarius-power-module-pcb
        path: pcb/*.zip
        if-no-files-found: error
        retention-days: 60

    - name: Upload Artifacts to Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: |
          pcb/aquarius-power-module-pcb-${{ github.event.release.tag_name }}.zip