# Aquarius - Automation Simplified
#
# @brief Git script for exporting PCB data for Power Module
# @note only runs when files are checked in
# @date 5/16/25
# @author cyberreefguru
# (c) CRG Makes 2025
name: Aquarius-Power-Module-Checkin-CI
on:
  push:
    paths:
      # - 'pcb/power-module.kicad_sch'
      - 'pcb/power-module.kicad_pcb'
      # - 'pcb/power-module-checkin.kibot.yaml'
      - '.github/workflows/power-module-checkin.yaml'
  workflow_dispatch:
    
jobs:
  export-ecad:
    name: Export ECAD
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
      
    steps:
    - name: Update system
      run: |
        echo "Working Directory $(pwd)"
        apt update
        apt -y install git zip

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: working/module-power

    - name: Checkout Extras
      uses: actions/checkout@v4
      with:
        repository: crgmakes/kicad-extras
        path: working/kicad-extras

    - name: Checkout CRGM Library
      uses: actions/checkout@v4
      with:
        repository: crgmakes/kicad-library
        path: working/kicad-library

    - name: Checkout PcbDraw Library
      uses: actions/checkout@v4
      with:
        repository: yaqwsx/PcbDraw-Lib
        path: working/PcbDraw-Lib

    - name: Checkout Fab Kit Library
      uses: actions/checkout@v4
      with:
        repository: bennymeg/Fabrication-Toolkit
        path: working/Fabrication-Toolkit

    - name: Update fonts
      run: |
        mkdir -p /usr/share/fonts/
        cp working/kicad-extras/fonts/* /usr/share/fonts/
        fc-cache -f -v

    - name: Update the PCB with git hash
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"    
        echo "ref: ${{ github.ref }}"
        echo "default: ${{ env.default }}"
        cd working/module-power/pcb
        sed -i "s!<<hash>>!${COMMIT}!" power-module.kicad_pcb
        #sed -i.bak 's|\${KICAD_USER_MODEL_DIR}|../crgm/models|g' pcb/power-module.kicad_pcb

    - name: Generate Fabrication Files
      run: |
        echo "Working Directory: ${{ github.workspace }}"
        cd working/module-power/
        kibot -c ../kicad-extras/kibot/crgm.kibot.yaml -e pcb/power-module.kicad_sch -b pcb/power-module.kicad_pcb -d production compress_jlc_4layer
        ls -AlF production
        # ls -AlF ${{ github.workspace }}/working/module-power/production

    # - name: Generate Export Files
    #   run: |
    #     cd pcb
    #     rm -rf production/
    #     kibot -c power-module-checkin.kibot.yaml -e power-module.kicad_sch -b power-module.kicad_pcb -d production
    #     cd production
    #     zip -r -j power-module-gerber.zip gerber/*
    #     rm -rf gerber/*
    #     mv power-module-gerber.zip gerber
    #     zip -r ../aquarius-power-module-pcb.zip * ../power-module.kicad_sch ../power-module.kicad_pcb

    # - name: Generate Production Files (Gerber, BOM, Position)
    #   run: |
    #     cd fabkit
    #     python3 -m plugins.cli -p ../pcb/power-module.kicad_pcb -u1 -t -f -e

    # - name: Zip Export Files
    #   run: |
    #     cd pcb
    #     echo `pwd`'/production'
    #     ls -AlF production
    #     cd production
    #     mkdir pnp
    #     mkdir gerber
    #     mkdir pcb
    #     mkdir netlist
    #     rm -rf backups
    #     mv bom.csv pnp/power-module-jlc-bom.csv
    #     mv positions.csv pnp/power-module-jlc-cpl.csv
    #     mv designators.csv pnp/power-module-jlc-designators.csv
    #     mv power-module.zip gerber
    #     cp ../power-module.kicad_sch pcb
    #     cp ../power-module.kicad_pcb pcb
    #     mv netlist.ipc netlist/power-module-netlist.ipc
    #     zip -r ../aquarius-power-module.zip *

    - name: Upload Files as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aquarius-power-module-pcb
        path: working/module-power/production/power-module-fab.zip
        if-no-files-found: error
        retention-days: 30