# Aquarius - Automation Simplified
#
# @brief Git script for exporting PCB data for Power Module
# @note only runs when files are released
# @date 5/16/25
# @author cyberreefguru
# (c) CRG Makes 2025
name: Aquarius-Power-Module-Release-CI
on:
  workflow_dispatch:
  release:
    types: [ published ]
    
jobs:
  export-ecad:
    name: Export ECAD
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
      
    steps:
    - name: Update system
      run: |
        apt update
        apt -y install git zip

    - name: Checkout Power Module Repository
      uses: actions/checkout@v4

    - name: Checkout Extras
      uses: actions/checkout@v4
      with:
        repository: crgmakes/kicad-extras
        path: extras

    - name: Checkout CRGM Library
      uses: actions/checkout@v4
      with:
        repository: crgmakes/kicad-library
        path: crgm

    - name: Checkout PcbDraw Library
      uses: actions/checkout@v4
      with:
        repository: yaqwsx/PcbDraw-Lib
        path: pcbdraw

    - name: Checkout Fab Kit Library
      uses: actions/checkout@v4
      with:
        repository: bennymeg/Fabrication-Toolkit
        path: fabkit

    - name: Get 3d packages
      run: |
        git clone https://gitlab.com/kicad/libraries/kicad-packages3D.git
        mkdir -p /usr/share/kicad/3dmodels
        mv ./kicad-packages3D/* /usr/share/kicad/3dmodels

    - name: Update fonts
      run: |
        mkdir -p /usr/share/fonts/
        cp extras/fonts/* /usr/share/fonts/
        fc-cache -f -v

    - name: Update the PCB with git hash
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"    
        echo "ref: ${{ github.ref }}"
        echo "default: ${{ env.default }}"
        sed -i "s!<<hash>>!${COMMIT}!" pcb/power-module.kicad_pcb
        sed -i.bak 's|\${KICAD_USER_MODEL_DIR}|../crgm/models|g' pcb/power-module.kicad_pcb

    # - name: Generate Single PCB Produciton Files
    #   run: |
    #     cd pcb
    #     rm -rf production/
    #     kibot -c power-module-release.kibot.yaml -e power-module.kicad_sch -b power-module.kicad_pcb -d production
    #     cd production
    #     zip -r -j power-module-gerber.zip gerber/*
    #     rm -rf gerber/*
    #     mv power-module-gerber.zip gerber
    #     zip -r ../aquarius-power-module-pcb.zip * ../power-module.kicad_sch ../power-module.kicad_pcb

    - name: Generate Production Files (Gerber, BOM, Position)
      run: |
        cd fabkit
        python3 -m plugins.cli -p ../pcb/power-module.kicad_pcb -u1 -t -f -e

    - name: Zip Export Files
      run: |
        cd pcb
        echo `pwd`'/production'
        ls -AlF production
        cd production
        mkdir pnp
        mkdir gerber
        mkdir pcb
        mkdir netlist
        rm -rf backups
        mv bom.csv pnp/power-module-jlc-bom.csv
        mv positions.csv pnp/power-module-jlc-cpl.csv
        mv designators.csv pnp/power-module-jlc-designators.csv
        mv power-module.zip gerber
        cp ../power-module.kicad_sch pcb
        cp ../power-module.kicad_pcb pcb
        mv netlist.ipc netlist/power-module-netlist.ipc
        zip -r ../aquarius-power-module.zip *

    - name: Generate Panel PCB
      run: |
        cd pcb/panel
        rm -rf production
        kibot -c power-module-panel-release.kibot.yaml -e ../power-module.kicad_sch -b ../power-module.kicad_pcb -d .

    - name: Generate Panel Production Files (Gerber, BOM, Position)
      run: |
        cd fabkit
        python3 -m plugins.cli -p ../pcb/panel/power-module-panel-2x2.kicad_pcb -u1 -t -f -e

    - name: Zip Export Files
      run: |
        cd pcb/panel
        echo `pwd`'/production'
        ls -AlF production
        cd production
        mkdir pnp
        mkdir gerber
        mkdir pcb
        mkdir netlist
        rm -rf backups
        mv bom.csv pnp/power-module-panel-2x2-jlc-bom.csv
        mv positions.csv pnp/power-module-panel-2x2-jlc-cpl.csv
        mv designators.csv pnp
        mv power-module-panel-2x2.zip gerber
        mv ../power-module-panel-2x2.kicad_pcb pcb
        mv netlist.ipc netlist/power-module-panel-2x2-netlist.ipc
        zip -r ../aquarius-power-module-panel.zip *

    - name: Generate Release Files
      if: github.event_name == 'release'
      run: |
        cd pcb
        cp aquarius-power-module-pcb.zip aquarius-power-module-pcb-${{ github.event.release.tag_name }}.zip
        cd panel
        cp aquarius-power-module-panel.zip aquarius-power-module-panel-${{ github.event.release.tag_name }}.zip

    - name: Upload Files as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aquarius-power-module-pcb
        path: pcb/*.zip
        if-no-files-found: error
        retention-days: 30

    - name: Upload Files as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aquarius-power-module-panel
        path: pcb/panel/*.zip
        if-no-files-found: error
        retention-days: 30

    - name: Upload Artifacts to Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: |
          pcb/aquarius-power-module-pcb-${{ github.event.release.tag_name }}.zip
          pcb/panel/aquarius-power-module-panel-${{ github.event.release.tag_name }}.zip






          