# Aquarius - Automation Simplified
#
# @brief Git script for exporting PCB data for Power Module
# @date 5/16/25
# @author cyberreefguru
# (c) CRG Makes 2025
name: Aquarius Power Module CI
on:
  push:
    paths:
      - 'pcb/power-module.kicad_sch'
      - 'pcb/power-module.kicad_pcb'
      - 'pcb/power-module.kibot.yaml'
      - '.github/workflows/power-module.yaml'
  workflow_dispatch:
  release:
    types: [ published ]
    
jobs:
  export-ecad:
    name: Export ECAD
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest
      
    steps:
    - name: Generate Short SHA Environment Variable
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      
    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        apt -y install git git-lfs zip librsvg2-bin imagemagick
        git lfs install

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: Extract branch name
      shell: bash
      run: |
        echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        echo "branch=${steps.extract_branch.outputs.branch} main=${env.main_branch}"
      # run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Update the PCBs with on default branch with git hash
      # if: github.event_name == 'release' || steps.extract_branch.outputs.branch == env.main_branch
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"    
        echo "ref: ${{ github.ref }}"
        echo "default: ${{ env.default }}"
        sed -i "s!<<hash>>!${COMMIT}!" pcb/power-module.kicad_pcb

    # - name: Update the PCBs with the git hash and BETA.
    #   if: steps.extract_branch.outputs.branch != env.main_branch
    #   run: |
    #     export COMMIT=$(git rev-parse --short HEAD)
    #     echo "COMMIT = ${COMMIT}"
    #     sed -i "s!<<hash>>!BETA-${COMMIT}!" pcb/power-module.kicad_pcb

    - name: Generate Export Files
      run: |
        cd pcb
        rm -rf production/
        kibot -c power-module.kibot.yaml -e power-module.kicad_sch -b power-module.kicad_pcb -d production
        zip -r -j aquarius-power-module-pcb.zip production/

# Zip and Upload
    - name: Upload Files as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aquarius-power-module-pcb.zip
        path: pcb/aquarius-power-module-pcb.zip
        if-no-files-found: error
        retention-days: 60

    - name: Upload Artifacts to Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: |
          pcb/aquarius-power-module-pcb-${{ github.event.release.tag_name }}.zip