# Aquarius - Automation Simplified
#
# @brief Git script for testing
# @date 5/25/25
# @author cyberreefguru
# (c) CRG Makes 2025

name: Aquarius-Test
on:
  workflow_dispatch:
    
jobs:
  test-clone:
    name: Test Cloning
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
      
    steps:
    - name: List Directory
      run: |
        echo "Directory '$(pwd)' Contents"
        ls -AlF
        mkdir working
        ls -AlF

    # - name: Update system
    #   run: |
    #     apt update
    #     apt -y install git zip

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: working/module-power

    - name: Checkout Extras
      uses: actions/checkout@v4
      with:
        repository: crgmakes/kicad-extras
        path: working/kicad-extras

    - name: Checkout CRGM Library
      uses: actions/checkout@v4
      with:
        repository: crgmakes/kicad-library
        path: working/kicad-library

    - name: Checkout PcbDraw Library
      uses: actions/checkout@v4
      with:
        repository: yaqwsx/PcbDraw-Lib
        path: working/PcbDraw-Lib

    - name: Checkout Fab Kit Library
      uses: actions/checkout@v4
      with:
        repository: bennymeg/Fabrication-Toolkit
        path: working/Fabrication-Toolkit

    - name: List Directory
      run: |
        cd working
        echo "Directory '$(pwd)' Contents"
        ls -AlF

  test-previous-clone:
      name: Test Previous Clone
      runs-on: ubuntu-latest
      container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
      needs: test-clone

      steps:
      - name: List Directory
        run: |
          echo "Directory '$(pwd)' Contents"
          ls -AlF
          # cd working
          # echo "Directory '$(pwd)' Contents"
          # ls -AlF




