# Aquarius - Automation Simplified
#
# @brief Git script for exporting PCB data for Power Module
# @date 5/16/25
# @author cyberreefguru
# (c) CRG Makes 2025
name: Aquarius Power Module CI
on:
  push:
    paths:
      - 'pcb/power-module.kicad_sch'
      - 'pcb/power-module.kicad_pcb'
      - 'pcb/power-module.kibot.yaml'
      - '.github/workflows/power-module.yaml'
  workflow_dispatch:
  release:
    types: [ published ]
    
jobs:
  export-ecad:
    name: Export ECAD
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
      
    steps:
    # - name: Generate Short SHA Environment Variable
    #   run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      
    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        # apt -y install git zip librsvg2-bin imagemagick
        apt -y install git zip

    - name: Checkout Power Module Repository
      uses: actions/checkout@v4
      with:
        repository: crgmakes/module-power
        path: power

    - name: Checkout Extras
      uses: actions/checkout@v4
      with:
        repository: crgmakes/kicad-extras
        path: extras

    - name: Checkout CRGM Library
      uses: actions/checkout@v4
      with:
        repository: crgmakes/kicad-library
        path: crgm

    # *** comment out to save time during testing ***

    # - name: Checkout PcbDraw Library
    #   uses: actions/checkout@v4
    #   with:
    #     repository: yaqwsx/PcbDraw-Lib
    #     path: pcbdraw

    # - name: Get 3d packages
    #   run: |
    #     git clone https://gitlab.com/kicad/libraries/kicad-packages3D.git
    #     mkdir -p /usr/share/kicad/3dmodels
    #     mv ./kicad-packages3D/* /usr/share/kicad/3dmodels

    - name: Update fonts
      run: |
        mkdir -p /usr/share/fonts/
        cp extras/fonts/* /usr/share/fonts/
        fc-cache -f -v

    - name: "What do we have?"
      run: |
        echo "Root Directory"
        ls -AlF

#     - name: Update the PCB with git hash
#       run: |
#         export COMMIT=$(git rev-parse --short HEAD)
#         echo "COMMIT = ${COMMIT}"    
#         echo "ref: ${{ github.ref }}"
#         echo "default: ${{ env.default }}"
#         sed -i "s!<<hash>>!${COMMIT}!" pcb/power-module.kicad_pcb
#         sed -i.bak 's|\${KICAD_USER_MODEL_DIR}|../crgm/models|g' pcb/power-module.kicad_pcb

#     - name: Generate Export Files
#       run: |
#         cd pcb
#         rm -rf production/
#         kibot -c power-module.kibot.yaml -e power-module.kicad_sch -b power-module.kicad_pcb -d production
#         cd production
#         # zip -r -j ../aquarius-power-module-gerber.zip gerber
#         # zip -r -j ../aquarius-power-module-pnp.zip pnp
#         # zip -r ../aquarius-power-module-doc.zip doc
#         # zip -r -j aquarius-power-module-pcb.zip production/
#         zip -r ../aquarius-power-module-pcb.zip * 

#     - name: Generate Release Files
#       if: github.event_name == 'release'
#       run: |
#         cd pcb
#         cp aquarius-power-module-pcb.zip aquarius-power-module-pcb-${{ github.event.release.tag_name }}.zip

# # Upload
#     - name: Upload Files as Artifacts
#       uses: actions/upload-artifact@v4
#       with:
#         name: aquarius-power-module-pcb
#         path: pcb/*.zip
#         if-no-files-found: error
#         retention-days: 60

#     - name: Upload Artifacts to Release
#       uses: softprops/action-gh-release@v1
#       if: github.event_name == 'release'
#       with:
#         files: |
#           pcb/aquarius-power-module-pcb-${{ github.event.release.tag_name }}.zip